import { Template } from "./types";

export const mockTemplates: Template[] = [
  {
    id: "1",
    title: "Master's in Data Science",
    icon: "🎓",
    category: "Academic Programs",
    programLevel: "Master's",
    industry: "Technology",
    description: "A comprehensive Master's program in Data Science with proven market demand",
    includes: [
      "Pre-filled industry sectors (Technology, Finance)",
      "Target regions (US: CA, NY, TX, WA, MA)",
      "Typical program duration: 48 weeks (12 months)",
      "Delivery format: Hybrid (60% online, 40% in-person)",
      "Financial model with industry benchmarks",
      "Common competitor programs for benchmarking",
    ],
    regions: ["US", "Canada"],
    typicalDuration: "48 weeks",
    usedBy: 47,
    avgDemandScore: 8.2,
    typicalResults: {
      avgDemandScore: 8.2,
      avgJobsFound: "1,200+",
      avgSalary: "$115,000",
      breakEvenMonths: "14-18 months",
    },
    deliveryFormat: "Hybrid (60% online, 40% in-person)",
    usageCount: 47,
    createdAt: "2024-06-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Leadership Development",
    icon: "💼",
    category: "Corporate Training",
    programLevel: "Certificate",
    industry: "Business",
    description: "Executive training program designed for corporate learning and development",
    includes: [
      "Executive training focus",
      "Corporate learning outcomes framework",
      "12-16 week duration",
      "ROI calculator preset",
      "Leadership competency assessments",
      "Corporate cohort management tools",
    ],
    regions: ["Global"],
    typicalDuration: "12-16 weeks",
    usedBy: 23,
    avgDemandScore: 7.5,
    typicalResults: {
      avgDemandScore: 7.5,
      avgJobsFound: "600+",
      avgSalary: "$95,000",
      breakEvenMonths: "8-12 months",
    },
    deliveryFormat: "Hybrid",
    usageCount: 23,
    createdAt: "2024-05-20T14:30:00Z",
  },
  {
    id: "3",
    title: "Cybersecurity Certificate",
    icon: "🔒",
    category: "Academic Programs",
    programLevel: "Certificate",
    industry: "Technology",
    description: "Professional cybersecurity certificate with global industry alignment",
    includes: [
      "Skills gap analysis preset",
      "Target regions (Global)",
      "24-week duration",
      "Online delivery format",
      "Industry certification mapping",
      "Hands-on lab environments",
    ],
    regions: ["Global"],
    typicalDuration: "24 weeks",
    usedBy: 89,
    avgDemandScore: 9.1,
    typicalResults: {
      avgDemandScore: 9.1,
      avgJobsFound: "1,800+",
      avgSalary: "$120,000",
      breakEvenMonths: "10-14 months",
    },
    deliveryFormat: "Online",
    usageCount: 89,
    createdAt: "2024-07-10T09:00:00Z",
  },
  {
    id: "4",
    title: "Healthcare Administration",
    icon: "🏥",
    category: "Academic Programs",
    programLevel: "Bachelor's",
    industry: "Healthcare",
    description: "Comprehensive healthcare administration program for aspiring healthcare leaders",
    includes: [
      "Healthcare sector specialization",
      "Target regions (US, Canada, Europe)",
      "36-week core program + internship",
      "Clinical placement requirements",
      "Healthcare finance modules",
      "Compliance and regulatory training",
    ],
    regions: ["US", "Canada", "Europe"],
    typicalDuration: "48 weeks",
    usedBy: 34,
    avgDemandScore: 8.0,
    typicalResults: {
      avgDemandScore: 8.0,
      avgJobsFound: "950+",
      avgSalary: "$70,000",
      breakEvenMonths: "16-20 months",
    },
    deliveryFormat: "Blended",
    usageCount: 34,
    createdAt: "2024-04-05T11:15:00Z",
  },
  {
    id: "5",
    title: "Financial Analysis Bootcamp",
    icon: "💰",
    category: "Corporate Training",
    programLevel: "Bootcamp",
    industry: "Finance",
    description: "Intensive financial analysis bootcamp for career changers",
    includes: [
      "Financial modeling focus",
      "Target regions (US, Europe)",
      "12-week intensive program",
      "Job placement support",
      "Industry tools training (Excel, Tableau, Bloomberg)",
      "Capstone projects with real datasets",
    ],
    regions: ["US", "Europe"],
    typicalDuration: "12 weeks",
    usedBy: 56,
    avgDemandScore: 8.7,
    typicalResults: {
      avgDemandScore: 8.7,
      avgJobsFound: "1,100+",
      avgSalary: "$105,000",
      breakEvenMonths: "9-11 months",
    },
    deliveryFormat: "In-person",
    usageCount: 56,
    createdAt: "2024-08-12T13:45:00Z",
  },
  {
    id: "6",
    title: "Government Workforce Development",
    icon: "🏛️",
    category: "Government Workforce",
    programLevel: "Certificate",
    industry: "Government",
    description: "Federal workforce development program with government standards compliance",
    includes: [
      "Government sector alignment",
      "Compliance with federal requirements",
      "20-week program duration",
      "Civil service exam prep",
      "Public administration modules",
      "Career pathway mapping",
    ],
    regions: ["US"],
    typicalDuration: "20 weeks",
    usedBy: 12,
    avgDemandScore: 7.2,
    typicalResults: {
      avgDemandScore: 7.2,
      avgJobsFound: "450+",
      avgSalary: "$65,000",
      breakEvenMonths: "18-24 months",
    },
    deliveryFormat: "Online",
    usageCount: 12,
    createdAt: "2024-03-22T10:30:00Z",
  },
];

export const recentlyUsedTemplateIds = ["1", "3", "5"];
