import { Project } from "./types";

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Cybersecurity Analyst Bootcamp",
    status: "complete",
    programLevel: "Professional Certificate",
    topic: "IT & Cybersecurity",
    demandScore: 8.5,
    jobCount: 247,
    avgSalary: 95000,
    competitors: 8,
    createdAt: "2025-01-06T10:00:00Z",
  },
  {
    id: "2",
    name: "Data Science for Beginners",
    status: "analyzing",
    programLevel: "Bachelor's Degree",
    topic: "Data Science",
    demandScore: 9.2,
    jobCount: 450,
    avgSalary: 110000,
    competitors: 5,
    createdAt: "2025-03-15T14:30:00Z",
  },
  {
    id: "3",
    name: "UX/UI Design Fundamentals",
    status: "draft",
    programLevel: "Beginner Course",
    topic: "Design",
    demandScore: 7.8,
    jobCount: 150,
    avgSalary: 80000,
    competitors: 12,
    createdAt: "2025-04-20T09:00:00Z",
  },
  {
    id: "4",
    name: "Cloud Computing with AWS",
    status: "archived",
    programLevel: "Advanced Diploma",
    topic: "Cloud Computing",
    demandScore: 8.9,
    jobCount: 300,
    avgSalary: 105000,
    competitors: 7,
    createdAt: "2024-11-10T11:00:00Z",
  },
];
