import { AuditLog } from "./types";

export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    eventId: "evt_abc123xyz",
    timestamp: new Date("2025-01-06T14:23:45Z"),
    eventType: "project.created",
    category: "project",
    user: "jane@university.edu",
    userId: "user_xyz789",
    ipAddress: "203.0.113.45",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    event: "Project created",
    description: "New project 'Master's in Sustainable Finance' created",
    details: {
      project_id: "proj_abc123",
      project_name: "Master's in Sustainable Finance",
      program_level: "master",
      target_regions: ["California, USA", "New York, USA"],
    },
    severity: "info",
    status: "success",
  },
  {
    id: "audit-2",
    eventId: "evt_def456uvw",
    timestamp: new Date("2025-01-06T14:18:30Z"),
    eventType: "system.report_generated",
    category: "system",
    user: "john@corporate.com",
    userId: "user_abc456",
    ipAddress: "198.51.100.22",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    event: "Report generated",
    description: "PDF report generated for project analysis",
    details: {
      project_id: "proj_def789",
      report_format: "PDF",
      report_type: "market_analysis",
      file_size: "2.4 MB",
    },
    severity: "info",
    status: "success",
  },
  {
    id: "audit-3",
    eventId: "evt_ghi789rst",
    timestamp: new Date("2025-01-06T14:15:20Z"),
    eventType: "admin.user_modified",
    category: "admin",
    user: "admin@arbpc.com",
    userId: "user_admin001",
    ipAddress: "10.0.0.1",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    event: "User tier changed",
    description: "User tier upgraded from Professional to Enterprise",
    details: {
      target_user_id: "user_xyz789",
      target_user_email: "jane@university.edu",
      old_tier: "professional",
      new_tier: "enterprise",
      upgrade_reason: "annual_renewal",
    },
    severity: "warning",
    status: "success",
  },
  {
    id: "audit-4",
    eventId: "evt_jkl012mno",
    timestamp: new Date("2025-01-06T14:12:15Z"),
    eventType: "user.login",
    category: "user",
    user: "sarah@gov.org",
    userId: "user_ghi012",
    ipAddress: "192.0.2.78",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64)",
    event: "Login successful",
    description: "User logged in successfully",
    details: {
      login_method: "email_password",
      mfa_enabled: true,
      session_duration: "120 minutes",
    },
    severity: "info",
    status: "success",
  },
  {
    id: "audit-5",
    eventId: "evt_pqr345stu",
    timestamp: new Date("2025-01-06T14:09:00Z"),
    eventType: "system.analysis_completed",
    category: "system",
    user: "system",
    userId: "system_user",
    ipAddress: "-",
    event: "Analysis completed",
    description: "AI analysis completed for project",
    details: {
      project_id: "proj_pqr789",
      analysis_type: "market_demand",
      duration_seconds: 847,
      completion_status: "successful",
      results_stored: true,
    },
    severity: "info",
    status: "success",
  },
  {
    id: "audit-6",
    eventId: "evt_vwx678yza",
    timestamp: new Date("2025-01-06T14:05:30Z"),
    eventType: "security.failed_login",
    category: "security",
    user: "mike@edtech.io",
    userId: "user_vwx678",
    ipAddress: "203.0.113.99",
    event: "Failed login (3x)",
    description: "Multiple failed login attempts detected",
    details: {
      failed_attempts: 3,
      time_period: "5 minutes",
      reason: "incorrect_password",
      account_locked: false,
    },
    severity: "warning",
    status: "failed",
  },
  {
    id: "audit-7",
    eventId: "evt_bcd901efg",
    timestamp: new Date("2025-01-06T13:55:20Z"),
    eventType: "project.deleted",
    category: "project",
    user: "alice@tech.com",
    userId: "user_bcd901",
    ipAddress: "198.51.100.88",
    event: "Project deleted",
    description: "Project archived and marked for deletion",
    details: {
      project_id: "proj_old123",
      project_name: "Legacy Project",
      deletion_reason: "user_requested",
      retention_days: 30,
    },
    severity: "warning",
    status: "success",
  },
  {
    id: "audit-8",
    eventId: "evt_hij234klm",
    timestamp: new Date("2025-01-06T13:45:00Z"),
    eventType: "subscription.upgraded",
    category: "subscription",
    user: "bob@startup.io",
    userId: "user_hij234",
    ipAddress: "203.0.113.150",
    event: "Subscription upgraded",
    description: "Annual subscription upgraded to Enterprise plan",
    details: {
      old_plan: "professional",
      new_plan: "enterprise",
      billing_cycle: "annual",
      total_cost: 9999,
      currency: "USD",
    },
    severity: "info",
    status: "success",
  },
  {
    id: "audit-9",
    eventId: "evt_nop567qrs",
    timestamp: new Date("2025-01-06T13:35:45Z"),
    eventType: "admin.settings_changed",
    category: "admin",
    user: "admin@arbpc.com",
    userId: "user_admin001",
    ipAddress: "10.0.0.1",
    event: "Settings changed",
    description: "Platform settings updated by administrator",
    details: {
      setting_name: "max_projects_per_user",
      old_value: 10,
      new_value: 25,
      change_timestamp: "2025-01-06T13:35:45Z",
    },
    severity: "warning",
    status: "success",
  },
  {
    id: "audit-10",
    eventId: "evt_tuv890wxyz",
    timestamp: new Date("2025-01-06T13:25:10Z"),
    eventType: "security.suspicious_activity",
    category: "security",
    user: "unknown",
    userId: "unknown_user",
    ipAddress: "203.0.113.200",
    event: "Suspicious activity detected",
    description: "Unusual access pattern detected from IP address",
    details: {
      activity_type: "rapid_requests",
      request_count: 150,
      time_period: "1 minute",
      endpoint: "/api/projects",
      action_taken: "rate_limit_applied",
    },
    severity: "critical",
    status: "partial",
  },
];
